/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "iwa_authserver.pb-c.h"
void   i_waserver_auth__log_reg_client__init
                     (IWAserverAuth__LogRegClient         *message)
{
  static IWAserverAuth__LogRegClient init_value = I_WASERVER_AUTH__LOG_REG_CLIENT__INIT;
  *message = init_value;
}
size_t i_waserver_auth__log_reg_client__get_packed_size
                     (const IWAserverAuth__LogRegClient *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &i_waserver_auth__log_reg_client__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t i_waserver_auth__log_reg_client__pack
                     (const IWAserverAuth__LogRegClient *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &i_waserver_auth__log_reg_client__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t i_waserver_auth__log_reg_client__pack_to_buffer
                     (const IWAserverAuth__LogRegClient *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &i_waserver_auth__log_reg_client__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
IWAserverAuth__LogRegClient *
       i_waserver_auth__log_reg_client__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (IWAserverAuth__LogRegClient *)
     protobuf_c_message_unpack (&i_waserver_auth__log_reg_client__descriptor,
                                allocator, len, data);
}
void   i_waserver_auth__log_reg_client__free_unpacked
                     (IWAserverAuth__LogRegClient *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &i_waserver_auth__log_reg_client__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   i_waserver_auth__log_reg_server__init
                     (IWAserverAuth__LogRegServer         *message)
{
  static IWAserverAuth__LogRegServer init_value = I_WASERVER_AUTH__LOG_REG_SERVER__INIT;
  *message = init_value;
}
size_t i_waserver_auth__log_reg_server__get_packed_size
                     (const IWAserverAuth__LogRegServer *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &i_waserver_auth__log_reg_server__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t i_waserver_auth__log_reg_server__pack
                     (const IWAserverAuth__LogRegServer *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &i_waserver_auth__log_reg_server__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t i_waserver_auth__log_reg_server__pack_to_buffer
                     (const IWAserverAuth__LogRegServer *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &i_waserver_auth__log_reg_server__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
IWAserverAuth__LogRegServer *
       i_waserver_auth__log_reg_server__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (IWAserverAuth__LogRegServer *)
     protobuf_c_message_unpack (&i_waserver_auth__log_reg_server__descriptor,
                                allocator, len, data);
}
void   i_waserver_auth__log_reg_server__free_unpacked
                     (IWAserverAuth__LogRegServer *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &i_waserver_auth__log_reg_server__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   i_waserver_auth__proof_client__init
                     (IWAserverAuth__ProofClient         *message)
{
  static IWAserverAuth__ProofClient init_value = I_WASERVER_AUTH__PROOF_CLIENT__INIT;
  *message = init_value;
}
size_t i_waserver_auth__proof_client__get_packed_size
                     (const IWAserverAuth__ProofClient *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &i_waserver_auth__proof_client__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t i_waserver_auth__proof_client__pack
                     (const IWAserverAuth__ProofClient *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &i_waserver_auth__proof_client__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t i_waserver_auth__proof_client__pack_to_buffer
                     (const IWAserverAuth__ProofClient *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &i_waserver_auth__proof_client__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
IWAserverAuth__ProofClient *
       i_waserver_auth__proof_client__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (IWAserverAuth__ProofClient *)
     protobuf_c_message_unpack (&i_waserver_auth__proof_client__descriptor,
                                allocator, len, data);
}
void   i_waserver_auth__proof_client__free_unpacked
                     (IWAserverAuth__ProofClient *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &i_waserver_auth__proof_client__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   i_waserver_auth__proof_server__init
                     (IWAserverAuth__ProofServer         *message)
{
  static IWAserverAuth__ProofServer init_value = I_WASERVER_AUTH__PROOF_SERVER__INIT;
  *message = init_value;
}
size_t i_waserver_auth__proof_server__get_packed_size
                     (const IWAserverAuth__ProofServer *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &i_waserver_auth__proof_server__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t i_waserver_auth__proof_server__pack
                     (const IWAserverAuth__ProofServer *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &i_waserver_auth__proof_server__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t i_waserver_auth__proof_server__pack_to_buffer
                     (const IWAserverAuth__ProofServer *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &i_waserver_auth__proof_server__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
IWAserverAuth__ProofServer *
       i_waserver_auth__proof_server__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (IWAserverAuth__ProofServer *)
     protobuf_c_message_unpack (&i_waserver_auth__proof_server__descriptor,
                                allocator, len, data);
}
void   i_waserver_auth__proof_server__free_unpacked
                     (IWAserverAuth__ProofServer *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &i_waserver_auth__proof_server__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   i_waserver_auth__server_list_client__init
                     (IWAserverAuth__ServerListClient         *message)
{
  static IWAserverAuth__ServerListClient init_value = I_WASERVER_AUTH__SERVER_LIST_CLIENT__INIT;
  *message = init_value;
}
size_t i_waserver_auth__server_list_client__get_packed_size
                     (const IWAserverAuth__ServerListClient *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &i_waserver_auth__server_list_client__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t i_waserver_auth__server_list_client__pack
                     (const IWAserverAuth__ServerListClient *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &i_waserver_auth__server_list_client__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t i_waserver_auth__server_list_client__pack_to_buffer
                     (const IWAserverAuth__ServerListClient *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &i_waserver_auth__server_list_client__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
IWAserverAuth__ServerListClient *
       i_waserver_auth__server_list_client__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (IWAserverAuth__ServerListClient *)
     protobuf_c_message_unpack (&i_waserver_auth__server_list_client__descriptor,
                                allocator, len, data);
}
void   i_waserver_auth__server_list_client__free_unpacked
                     (IWAserverAuth__ServerListClient *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &i_waserver_auth__server_list_client__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   i_waserver_auth__server_list_server__server__character__init
                     (IWAserverAuth__ServerListServer__Server__Character         *message)
{
  static IWAserverAuth__ServerListServer__Server__Character init_value = I_WASERVER_AUTH__SERVER_LIST_SERVER__SERVER__CHARACTER__INIT;
  *message = init_value;
}
void   i_waserver_auth__server_list_server__server__init
                     (IWAserverAuth__ServerListServer__Server         *message)
{
  static IWAserverAuth__ServerListServer__Server init_value = I_WASERVER_AUTH__SERVER_LIST_SERVER__SERVER__INIT;
  *message = init_value;
}
void   i_waserver_auth__server_list_server__init
                     (IWAserverAuth__ServerListServer         *message)
{
  static IWAserverAuth__ServerListServer init_value = I_WASERVER_AUTH__SERVER_LIST_SERVER__INIT;
  *message = init_value;
}
size_t i_waserver_auth__server_list_server__get_packed_size
                     (const IWAserverAuth__ServerListServer *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &i_waserver_auth__server_list_server__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t i_waserver_auth__server_list_server__pack
                     (const IWAserverAuth__ServerListServer *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &i_waserver_auth__server_list_server__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t i_waserver_auth__server_list_server__pack_to_buffer
                     (const IWAserverAuth__ServerListServer *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &i_waserver_auth__server_list_server__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
IWAserverAuth__ServerListServer *
       i_waserver_auth__server_list_server__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (IWAserverAuth__ServerListServer *)
     protobuf_c_message_unpack (&i_waserver_auth__server_list_server__descriptor,
                                allocator, len, data);
}
void   i_waserver_auth__server_list_server__free_unpacked
                     (IWAserverAuth__ServerListServer *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &i_waserver_auth__server_list_server__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor i_waserver_auth__log_reg_client__field_descriptors[11] =
{
  {
    "gamename",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(IWAserverAuth__LogRegClient, gamename),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "version1",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(IWAserverAuth__LogRegClient, version1),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "version2",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(IWAserverAuth__LogRegClient, version2),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "version3",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(IWAserverAuth__LogRegClient, version3),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "build",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(IWAserverAuth__LogRegClient, build),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "platform",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(IWAserverAuth__LogRegClient, platform),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "os",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(IWAserverAuth__LogRegClient, os),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "country",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(IWAserverAuth__LogRegClient, country),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timezone_bias",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_SINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(IWAserverAuth__LogRegClient, timezone_bias),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "username",
    10,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(IWAserverAuth__LogRegClient, username),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "password_hash",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(IWAserverAuth__LogRegClient, password_hash),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned i_waserver_auth__log_reg_client__field_indices_by_name[] = {
  4,   /* field[4] = build */
  7,   /* field[7] = country */
  0,   /* field[0] = gamename */
  6,   /* field[6] = os */
  10,   /* field[10] = password_hash */
  5,   /* field[5] = platform */
  8,   /* field[8] = timezone_bias */
  9,   /* field[9] = username */
  1,   /* field[1] = version1 */
  2,   /* field[2] = version2 */
  3,   /* field[3] = version3 */
};
static const ProtobufCIntRange i_waserver_auth__log_reg_client__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 11 }
};
const ProtobufCMessageDescriptor i_waserver_auth__log_reg_client__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "iWAserverAuth.LogRegClient",
  "LogRegClient",
  "IWAserverAuth__LogRegClient",
  "iWAserverAuth",
  sizeof(IWAserverAuth__LogRegClient),
  11,
  i_waserver_auth__log_reg_client__field_descriptors,
  i_waserver_auth__log_reg_client__field_indices_by_name,
  1,  i_waserver_auth__log_reg_client__number_ranges,
  (ProtobufCMessageInit) i_waserver_auth__log_reg_client__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor i_waserver_auth__log_reg_server__field_descriptors[5] =
{
  {
    "result",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(IWAserverAuth__LogRegServer, result),
    &i_waserver_auth__result_code__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "B",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(IWAserverAuth__LogRegServer, has_b),
    PROTOBUF_C_OFFSETOF(IWAserverAuth__LogRegServer, b),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "g",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(IWAserverAuth__LogRegServer, has_g),
    PROTOBUF_C_OFFSETOF(IWAserverAuth__LogRegServer, g),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "N",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(IWAserverAuth__LogRegServer, has_n),
    PROTOBUF_C_OFFSETOF(IWAserverAuth__LogRegServer, n),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "s",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(IWAserverAuth__LogRegServer, has_s),
    PROTOBUF_C_OFFSETOF(IWAserverAuth__LogRegServer, s),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned i_waserver_auth__log_reg_server__field_indices_by_name[] = {
  1,   /* field[1] = B */
  3,   /* field[3] = N */
  2,   /* field[2] = g */
  0,   /* field[0] = result */
  4,   /* field[4] = s */
};
static const ProtobufCIntRange i_waserver_auth__log_reg_server__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor i_waserver_auth__log_reg_server__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "iWAserverAuth.LogRegServer",
  "LogRegServer",
  "IWAserverAuth__LogRegServer",
  "iWAserverAuth",
  sizeof(IWAserverAuth__LogRegServer),
  5,
  i_waserver_auth__log_reg_server__field_descriptors,
  i_waserver_auth__log_reg_server__field_indices_by_name,
  1,  i_waserver_auth__log_reg_server__number_ranges,
  (ProtobufCMessageInit) i_waserver_auth__log_reg_server__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor i_waserver_auth__proof_client__field_descriptors[2] =
{
  {
    "A",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(IWAserverAuth__ProofClient, a),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "M1",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(IWAserverAuth__ProofClient, m1),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned i_waserver_auth__proof_client__field_indices_by_name[] = {
  0,   /* field[0] = A */
  1,   /* field[1] = M1 */
};
static const ProtobufCIntRange i_waserver_auth__proof_client__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor i_waserver_auth__proof_client__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "iWAserverAuth.ProofClient",
  "ProofClient",
  "IWAserverAuth__ProofClient",
  "iWAserverAuth",
  sizeof(IWAserverAuth__ProofClient),
  2,
  i_waserver_auth__proof_client__field_descriptors,
  i_waserver_auth__proof_client__field_indices_by_name,
  1,  i_waserver_auth__proof_client__number_ranges,
  (ProtobufCMessageInit) i_waserver_auth__proof_client__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor i_waserver_auth__proof_server__field_descriptors[1] =
{
  {
    "result",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(IWAserverAuth__ProofServer, result),
    &i_waserver_auth__result_code__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned i_waserver_auth__proof_server__field_indices_by_name[] = {
  0,   /* field[0] = result */
};
static const ProtobufCIntRange i_waserver_auth__proof_server__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor i_waserver_auth__proof_server__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "iWAserverAuth.ProofServer",
  "ProofServer",
  "IWAserverAuth__ProofServer",
  "iWAserverAuth",
  sizeof(IWAserverAuth__ProofServer),
  1,
  i_waserver_auth__proof_server__field_descriptors,
  i_waserver_auth__proof_server__field_indices_by_name,
  1,  i_waserver_auth__proof_server__number_ranges,
  (ProtobufCMessageInit) i_waserver_auth__proof_server__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor i_waserver_auth__server_list_client__field_descriptors[1] =
{
  {
    "reserved",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(IWAserverAuth__ServerListClient, reserved),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned i_waserver_auth__server_list_client__field_indices_by_name[] = {
  0,   /* field[0] = reserved */
};
static const ProtobufCIntRange i_waserver_auth__server_list_client__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor i_waserver_auth__server_list_client__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "iWAserverAuth.ServerListClient",
  "ServerListClient",
  "IWAserverAuth__ServerListClient",
  "iWAserverAuth",
  sizeof(IWAserverAuth__ServerListClient),
  1,
  i_waserver_auth__server_list_client__field_descriptors,
  i_waserver_auth__server_list_client__field_indices_by_name,
  1,  i_waserver_auth__server_list_client__number_ranges,
  (ProtobufCMessageInit) i_waserver_auth__server_list_client__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor i_waserver_auth__server_list_server__server__character__field_descriptors[5] =
{
  {
    "cid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(IWAserverAuth__ServerListServer__Server__Character, cid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(IWAserverAuth__ServerListServer__Server__Character, name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "grade",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(IWAserverAuth__ServerListServer__Server__Character, grade),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "race",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(IWAserverAuth__ServerListServer__Server__Character, race),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nation",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(IWAserverAuth__ServerListServer__Server__Character, nation),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned i_waserver_auth__server_list_server__server__character__field_indices_by_name[] = {
  0,   /* field[0] = cid */
  2,   /* field[2] = grade */
  1,   /* field[1] = name */
  4,   /* field[4] = nation */
  3,   /* field[3] = race */
};
static const ProtobufCIntRange i_waserver_auth__server_list_server__server__character__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor i_waserver_auth__server_list_server__server__character__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "iWAserverAuth.ServerListServer.Server.Character",
  "Character",
  "IWAserverAuth__ServerListServer__Server__Character",
  "iWAserverAuth",
  sizeof(IWAserverAuth__ServerListServer__Server__Character),
  5,
  i_waserver_auth__server_list_server__server__character__field_descriptors,
  i_waserver_auth__server_list_server__server__character__field_indices_by_name,
  1,  i_waserver_auth__server_list_server__server__character__number_ranges,
  (ProtobufCMessageInit) i_waserver_auth__server_list_server__server__character__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor i_waserver_auth__server_list_server__server__field_descriptors[9] =
{
  {
    "sid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(IWAserverAuth__ServerListServer__Server, sid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "region",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(IWAserverAuth__ServerListServer__Server, region),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(IWAserverAuth__ServerListServer__Server, status),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(IWAserverAuth__ServerListServer__Server, name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hit",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(IWAserverAuth__ServerListServer__Server, hit),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "address",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(IWAserverAuth__ServerListServer__Server, address),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "port",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(IWAserverAuth__ServerListServer__Server, port),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "char_num",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(IWAserverAuth__ServerListServer__Server, char_num),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "characters",
    9,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(IWAserverAuth__ServerListServer__Server, n_characters),
    PROTOBUF_C_OFFSETOF(IWAserverAuth__ServerListServer__Server, characters),
    &i_waserver_auth__server_list_server__server__character__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned i_waserver_auth__server_list_server__server__field_indices_by_name[] = {
  5,   /* field[5] = address */
  7,   /* field[7] = char_num */
  8,   /* field[8] = characters */
  4,   /* field[4] = hit */
  3,   /* field[3] = name */
  6,   /* field[6] = port */
  1,   /* field[1] = region */
  0,   /* field[0] = sid */
  2,   /* field[2] = status */
};
static const ProtobufCIntRange i_waserver_auth__server_list_server__server__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor i_waserver_auth__server_list_server__server__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "iWAserverAuth.ServerListServer.Server",
  "Server",
  "IWAserverAuth__ServerListServer__Server",
  "iWAserverAuth",
  sizeof(IWAserverAuth__ServerListServer__Server),
  9,
  i_waserver_auth__server_list_server__server__field_descriptors,
  i_waserver_auth__server_list_server__server__field_indices_by_name,
  1,  i_waserver_auth__server_list_server__server__number_ranges,
  (ProtobufCMessageInit) i_waserver_auth__server_list_server__server__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor i_waserver_auth__server_list_server__field_descriptors[2] =
{
  {
    "num",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(IWAserverAuth__ServerListServer, num),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "servers",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(IWAserverAuth__ServerListServer, n_servers),
    PROTOBUF_C_OFFSETOF(IWAserverAuth__ServerListServer, servers),
    &i_waserver_auth__server_list_server__server__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned i_waserver_auth__server_list_server__field_indices_by_name[] = {
  0,   /* field[0] = num */
  1,   /* field[1] = servers */
};
static const ProtobufCIntRange i_waserver_auth__server_list_server__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor i_waserver_auth__server_list_server__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "iWAserverAuth.ServerListServer",
  "ServerListServer",
  "IWAserverAuth__ServerListServer",
  "iWAserverAuth",
  sizeof(IWAserverAuth__ServerListServer),
  2,
  i_waserver_auth__server_list_server__field_descriptors,
  i_waserver_auth__server_list_server__field_indices_by_name,
  1,  i_waserver_auth__server_list_server__number_ranges,
  (ProtobufCMessageInit) i_waserver_auth__server_list_server__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue i_waserver_auth__result_code__enum_values_by_number[13] =
{
  { "SUCCESS", "I_WASERVER_AUTH__RESULT_CODE__SUCCESS", 0 },
  { "UNKNOWN_ERROR", "I_WASERVER_AUTH__RESULT_CODE__UNKNOWN_ERROR", 10 },
  { "UNPACK_MESSAGE_ERROR", "I_WASERVER_AUTH__RESULT_CODE__UNPACK_MESSAGE_ERROR", 20 },
  { "REG_USERNAME_EMPTY", "I_WASERVER_AUTH__RESULT_CODE__REG_USERNAME_EMPTY", 100 },
  { "REG_PASSWORD_EMPTY", "I_WASERVER_AUTH__RESULT_CODE__REG_PASSWORD_EMPTY", 101 },
  { "REG_DB_INSERT_ERROR", "I_WASERVER_AUTH__RESULT_CODE__REG_DB_INSERT_ERROR", 102 },
  { "LOGON_USERNAME_EMPTY", "I_WASERVER_AUTH__RESULT_CODE__LOGON_USERNAME_EMPTY", 200 },
  { "LOGON_DB_QUERY_ERROR", "I_WASERVER_AUTH__RESULT_CODE__LOGON_DB_QUERY_ERROR", 201 },
  { "LOGON_ACCOUNT_NOEXIST", "I_WASERVER_AUTH__RESULT_CODE__LOGON_ACCOUNT_NOEXIST", 202 },
  { "PROOF_AVALUE_INCORRECT", "I_WASERVER_AUTH__RESULT_CODE__PROOF_AVALUE_INCORRECT", 300 },
  { "PROOF_M1VALUE_INCORRECT", "I_WASERVER_AUTH__RESULT_CODE__PROOF_M1VALUE_INCORRECT", 301 },
  { "PROOF_MVALUE_UNMATCH", "I_WASERVER_AUTH__RESULT_CODE__PROOF_MVALUE_UNMATCH", 302 },
  { "PROOF_DB_UPDATE_ERROR", "I_WASERVER_AUTH__RESULT_CODE__PROOF_DB_UPDATE_ERROR", 303 },
};
static const ProtobufCIntRange i_waserver_auth__result_code__value_ranges[] = {
{0, 0},{10, 1},{20, 2},{100, 3},{200, 6},{300, 9},{0, 13}
};
const ProtobufCEnumValueIndex i_waserver_auth__result_code__enum_values_by_name[13] =
{
  { "LOGON_ACCOUNT_NOEXIST", 8 },
  { "LOGON_DB_QUERY_ERROR", 7 },
  { "LOGON_USERNAME_EMPTY", 6 },
  { "PROOF_AVALUE_INCORRECT", 9 },
  { "PROOF_DB_UPDATE_ERROR", 12 },
  { "PROOF_M1VALUE_INCORRECT", 10 },
  { "PROOF_MVALUE_UNMATCH", 11 },
  { "REG_DB_INSERT_ERROR", 5 },
  { "REG_PASSWORD_EMPTY", 4 },
  { "REG_USERNAME_EMPTY", 3 },
  { "SUCCESS", 0 },
  { "UNKNOWN_ERROR", 1 },
  { "UNPACK_MESSAGE_ERROR", 2 },
};
const ProtobufCEnumDescriptor i_waserver_auth__result_code__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "iWAserverAuth.resultCode",
  "resultCode",
  "IWAserverAuth__ResultCode",
  "iWAserverAuth",
  13,
  i_waserver_auth__result_code__enum_values_by_number,
  13,
  i_waserver_auth__result_code__enum_values_by_name,
  6,
  i_waserver_auth__result_code__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
