/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_iwa_5fgameserver_2eproto__INCLUDED
#define PROTOBUF_C_iwa_5fgameserver_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _IWAserverGame__AuthChallengeServer IWAserverGame__AuthChallengeServer;
typedef struct _IWAserverGame__AuthSessionClient IWAserverGame__AuthSessionClient;
typedef struct _IWAserverGame__AuthResponseServer IWAserverGame__AuthResponseServer;
typedef struct _IWAserverGame__Character IWAserverGame__Character;
typedef struct _IWAserverGame__CharEnumClient IWAserverGame__CharEnumClient;
typedef struct _IWAserverGame__CharEnumServer IWAserverGame__CharEnumServer;
typedef struct _IWAserverGame__CharCreateClient IWAserverGame__CharCreateClient;
typedef struct _IWAserverGame__CharCreateServer IWAserverGame__CharCreateServer;
typedef struct _IWAserverGame__CharDeleteClient IWAserverGame__CharDeleteClient;
typedef struct _IWAserverGame__CharDeleteServer IWAserverGame__CharDeleteServer;
typedef struct _IWAserverGame__PlayerLoginClient IWAserverGame__PlayerLoginClient;


/* --- enums --- */

typedef enum _IWAserverGame__ResultCode {
  I_WASERVER_GAME__RESULT_CODE__SUCCESS = 0,
  I_WASERVER_GAME__RESULT_CODE__UNKNOWN_ERROR = 10,
  I_WASERVER_GAME__RESULT_CODE__UNPACK_MESSAGE_ERROR = 20,
  I_WASERVER_GAME__RESULT_CODE__AUTH_RESPONSE_DB_QUERY_ERROR = 100,
  I_WASERVER_GAME__RESULT_CODE__AUTH_RESPONSE_ACCOUNT_NOEXIST = 101,
  I_WASERVER_GAME__RESULT_CODE__AUTH_RESPONSE_HASH_CHECK_ERROR = 102,
  I_WASERVER_GAME__RESULT_CODE__CHAR_CREATE_ILLEGAL_NAME = 200,
  I_WASERVER_GAME__RESULT_CODE__CHAR_CREATE_DB_INSERT_ERROR = 201,
  I_WASERVER_GAME__RESULT_CODE__CHAR_DELETE_DB_DELETE_ERROR = 210
} IWAserverGame__ResultCode;

/* --- messages --- */

struct  _IWAserverGame__AuthChallengeServer
{
  ProtobufCMessage base;
  uint32_t seed;
};
#define I_WASERVER_GAME__AUTH_CHALLENGE_SERVER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&i_waserver_game__auth_challenge_server__descriptor) \
    , 0 }


struct  _IWAserverGame__AuthSessionClient
{
  ProtobufCMessage base;
  uint32_t build;
  char *username;
  uint32_t seed;
  ProtobufCBinaryData d;
};
#define I_WASERVER_GAME__AUTH_SESSION_CLIENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&i_waserver_game__auth_session_client__descriptor) \
    , 0, NULL, 0, {0,NULL} }


struct  _IWAserverGame__AuthResponseServer
{
  ProtobufCMessage base;
  IWAserverGame__ResultCode result;
};
#define I_WASERVER_GAME__AUTH_RESPONSE_SERVER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&i_waserver_game__auth_response_server__descriptor) \
    , 0 }


struct  _IWAserverGame__Character
{
  ProtobufCMessage base;
  uint32_t cid;
  char *name;
  uint32_t grade;
  uint32_t race;
  uint32_t nation;
};
#define I_WASERVER_GAME__CHARACTER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&i_waserver_game__character__descriptor) \
    , 0, NULL, 0, 0, 0 }


struct  _IWAserverGame__CharEnumClient
{
  ProtobufCMessage base;
  uint32_t reserved;
};
#define I_WASERVER_GAME__CHAR_ENUM_CLIENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&i_waserver_game__char_enum_client__descriptor) \
    , 0 }


struct  _IWAserverGame__CharEnumServer
{
  ProtobufCMessage base;
  uint32_t char_num;
  size_t n_characters;
  IWAserverGame__Character **characters;
};
#define I_WASERVER_GAME__CHAR_ENUM_SERVER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&i_waserver_game__char_enum_server__descriptor) \
    , 0, 0,NULL }


struct  _IWAserverGame__CharCreateClient
{
  ProtobufCMessage base;
  char *name;
  uint32_t race;
  uint32_t nation;
};
#define I_WASERVER_GAME__CHAR_CREATE_CLIENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&i_waserver_game__char_create_client__descriptor) \
    , NULL, 0, 0 }


struct  _IWAserverGame__CharCreateServer
{
  ProtobufCMessage base;
  IWAserverGame__ResultCode result;
  uint32_t cid;
};
#define I_WASERVER_GAME__CHAR_CREATE_SERVER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&i_waserver_game__char_create_server__descriptor) \
    , 0, 0 }


struct  _IWAserverGame__CharDeleteClient
{
  ProtobufCMessage base;
  uint32_t cid;
};
#define I_WASERVER_GAME__CHAR_DELETE_CLIENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&i_waserver_game__char_delete_client__descriptor) \
    , 0 }


struct  _IWAserverGame__CharDeleteServer
{
  ProtobufCMessage base;
  IWAserverGame__ResultCode result;
};
#define I_WASERVER_GAME__CHAR_DELETE_SERVER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&i_waserver_game__char_delete_server__descriptor) \
    , 0 }


struct  _IWAserverGame__PlayerLoginClient
{
  ProtobufCMessage base;
  uint32_t cid;
};
#define I_WASERVER_GAME__PLAYER_LOGIN_CLIENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&i_waserver_game__player_login_client__descriptor) \
    , 0 }


/* IWAserverGame__AuthChallengeServer methods */
void   i_waserver_game__auth_challenge_server__init
                     (IWAserverGame__AuthChallengeServer         *message);
size_t i_waserver_game__auth_challenge_server__get_packed_size
                     (const IWAserverGame__AuthChallengeServer   *message);
size_t i_waserver_game__auth_challenge_server__pack
                     (const IWAserverGame__AuthChallengeServer   *message,
                      uint8_t             *out);
size_t i_waserver_game__auth_challenge_server__pack_to_buffer
                     (const IWAserverGame__AuthChallengeServer   *message,
                      ProtobufCBuffer     *buffer);
IWAserverGame__AuthChallengeServer *
       i_waserver_game__auth_challenge_server__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   i_waserver_game__auth_challenge_server__free_unpacked
                     (IWAserverGame__AuthChallengeServer *message,
                      ProtobufCAllocator *allocator);
/* IWAserverGame__AuthSessionClient methods */
void   i_waserver_game__auth_session_client__init
                     (IWAserverGame__AuthSessionClient         *message);
size_t i_waserver_game__auth_session_client__get_packed_size
                     (const IWAserverGame__AuthSessionClient   *message);
size_t i_waserver_game__auth_session_client__pack
                     (const IWAserverGame__AuthSessionClient   *message,
                      uint8_t             *out);
size_t i_waserver_game__auth_session_client__pack_to_buffer
                     (const IWAserverGame__AuthSessionClient   *message,
                      ProtobufCBuffer     *buffer);
IWAserverGame__AuthSessionClient *
       i_waserver_game__auth_session_client__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   i_waserver_game__auth_session_client__free_unpacked
                     (IWAserverGame__AuthSessionClient *message,
                      ProtobufCAllocator *allocator);
/* IWAserverGame__AuthResponseServer methods */
void   i_waserver_game__auth_response_server__init
                     (IWAserverGame__AuthResponseServer         *message);
size_t i_waserver_game__auth_response_server__get_packed_size
                     (const IWAserverGame__AuthResponseServer   *message);
size_t i_waserver_game__auth_response_server__pack
                     (const IWAserverGame__AuthResponseServer   *message,
                      uint8_t             *out);
size_t i_waserver_game__auth_response_server__pack_to_buffer
                     (const IWAserverGame__AuthResponseServer   *message,
                      ProtobufCBuffer     *buffer);
IWAserverGame__AuthResponseServer *
       i_waserver_game__auth_response_server__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   i_waserver_game__auth_response_server__free_unpacked
                     (IWAserverGame__AuthResponseServer *message,
                      ProtobufCAllocator *allocator);
/* IWAserverGame__Character methods */
void   i_waserver_game__character__init
                     (IWAserverGame__Character         *message);
size_t i_waserver_game__character__get_packed_size
                     (const IWAserverGame__Character   *message);
size_t i_waserver_game__character__pack
                     (const IWAserverGame__Character   *message,
                      uint8_t             *out);
size_t i_waserver_game__character__pack_to_buffer
                     (const IWAserverGame__Character   *message,
                      ProtobufCBuffer     *buffer);
IWAserverGame__Character *
       i_waserver_game__character__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   i_waserver_game__character__free_unpacked
                     (IWAserverGame__Character *message,
                      ProtobufCAllocator *allocator);
/* IWAserverGame__CharEnumClient methods */
void   i_waserver_game__char_enum_client__init
                     (IWAserverGame__CharEnumClient         *message);
size_t i_waserver_game__char_enum_client__get_packed_size
                     (const IWAserverGame__CharEnumClient   *message);
size_t i_waserver_game__char_enum_client__pack
                     (const IWAserverGame__CharEnumClient   *message,
                      uint8_t             *out);
size_t i_waserver_game__char_enum_client__pack_to_buffer
                     (const IWAserverGame__CharEnumClient   *message,
                      ProtobufCBuffer     *buffer);
IWAserverGame__CharEnumClient *
       i_waserver_game__char_enum_client__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   i_waserver_game__char_enum_client__free_unpacked
                     (IWAserverGame__CharEnumClient *message,
                      ProtobufCAllocator *allocator);
/* IWAserverGame__CharEnumServer methods */
void   i_waserver_game__char_enum_server__init
                     (IWAserverGame__CharEnumServer         *message);
size_t i_waserver_game__char_enum_server__get_packed_size
                     (const IWAserverGame__CharEnumServer   *message);
size_t i_waserver_game__char_enum_server__pack
                     (const IWAserverGame__CharEnumServer   *message,
                      uint8_t             *out);
size_t i_waserver_game__char_enum_server__pack_to_buffer
                     (const IWAserverGame__CharEnumServer   *message,
                      ProtobufCBuffer     *buffer);
IWAserverGame__CharEnumServer *
       i_waserver_game__char_enum_server__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   i_waserver_game__char_enum_server__free_unpacked
                     (IWAserverGame__CharEnumServer *message,
                      ProtobufCAllocator *allocator);
/* IWAserverGame__CharCreateClient methods */
void   i_waserver_game__char_create_client__init
                     (IWAserverGame__CharCreateClient         *message);
size_t i_waserver_game__char_create_client__get_packed_size
                     (const IWAserverGame__CharCreateClient   *message);
size_t i_waserver_game__char_create_client__pack
                     (const IWAserverGame__CharCreateClient   *message,
                      uint8_t             *out);
size_t i_waserver_game__char_create_client__pack_to_buffer
                     (const IWAserverGame__CharCreateClient   *message,
                      ProtobufCBuffer     *buffer);
IWAserverGame__CharCreateClient *
       i_waserver_game__char_create_client__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   i_waserver_game__char_create_client__free_unpacked
                     (IWAserverGame__CharCreateClient *message,
                      ProtobufCAllocator *allocator);
/* IWAserverGame__CharCreateServer methods */
void   i_waserver_game__char_create_server__init
                     (IWAserverGame__CharCreateServer         *message);
size_t i_waserver_game__char_create_server__get_packed_size
                     (const IWAserverGame__CharCreateServer   *message);
size_t i_waserver_game__char_create_server__pack
                     (const IWAserverGame__CharCreateServer   *message,
                      uint8_t             *out);
size_t i_waserver_game__char_create_server__pack_to_buffer
                     (const IWAserverGame__CharCreateServer   *message,
                      ProtobufCBuffer     *buffer);
IWAserverGame__CharCreateServer *
       i_waserver_game__char_create_server__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   i_waserver_game__char_create_server__free_unpacked
                     (IWAserverGame__CharCreateServer *message,
                      ProtobufCAllocator *allocator);
/* IWAserverGame__CharDeleteClient methods */
void   i_waserver_game__char_delete_client__init
                     (IWAserverGame__CharDeleteClient         *message);
size_t i_waserver_game__char_delete_client__get_packed_size
                     (const IWAserverGame__CharDeleteClient   *message);
size_t i_waserver_game__char_delete_client__pack
                     (const IWAserverGame__CharDeleteClient   *message,
                      uint8_t             *out);
size_t i_waserver_game__char_delete_client__pack_to_buffer
                     (const IWAserverGame__CharDeleteClient   *message,
                      ProtobufCBuffer     *buffer);
IWAserverGame__CharDeleteClient *
       i_waserver_game__char_delete_client__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   i_waserver_game__char_delete_client__free_unpacked
                     (IWAserverGame__CharDeleteClient *message,
                      ProtobufCAllocator *allocator);
/* IWAserverGame__CharDeleteServer methods */
void   i_waserver_game__char_delete_server__init
                     (IWAserverGame__CharDeleteServer         *message);
size_t i_waserver_game__char_delete_server__get_packed_size
                     (const IWAserverGame__CharDeleteServer   *message);
size_t i_waserver_game__char_delete_server__pack
                     (const IWAserverGame__CharDeleteServer   *message,
                      uint8_t             *out);
size_t i_waserver_game__char_delete_server__pack_to_buffer
                     (const IWAserverGame__CharDeleteServer   *message,
                      ProtobufCBuffer     *buffer);
IWAserverGame__CharDeleteServer *
       i_waserver_game__char_delete_server__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   i_waserver_game__char_delete_server__free_unpacked
                     (IWAserverGame__CharDeleteServer *message,
                      ProtobufCAllocator *allocator);
/* IWAserverGame__PlayerLoginClient methods */
void   i_waserver_game__player_login_client__init
                     (IWAserverGame__PlayerLoginClient         *message);
size_t i_waserver_game__player_login_client__get_packed_size
                     (const IWAserverGame__PlayerLoginClient   *message);
size_t i_waserver_game__player_login_client__pack
                     (const IWAserverGame__PlayerLoginClient   *message,
                      uint8_t             *out);
size_t i_waserver_game__player_login_client__pack_to_buffer
                     (const IWAserverGame__PlayerLoginClient   *message,
                      ProtobufCBuffer     *buffer);
IWAserverGame__PlayerLoginClient *
       i_waserver_game__player_login_client__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   i_waserver_game__player_login_client__free_unpacked
                     (IWAserverGame__PlayerLoginClient *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*IWAserverGame__AuthChallengeServer_Closure)
                 (const IWAserverGame__AuthChallengeServer *message,
                  void *closure_data);
typedef void (*IWAserverGame__AuthSessionClient_Closure)
                 (const IWAserverGame__AuthSessionClient *message,
                  void *closure_data);
typedef void (*IWAserverGame__AuthResponseServer_Closure)
                 (const IWAserverGame__AuthResponseServer *message,
                  void *closure_data);
typedef void (*IWAserverGame__Character_Closure)
                 (const IWAserverGame__Character *message,
                  void *closure_data);
typedef void (*IWAserverGame__CharEnumClient_Closure)
                 (const IWAserverGame__CharEnumClient *message,
                  void *closure_data);
typedef void (*IWAserverGame__CharEnumServer_Closure)
                 (const IWAserverGame__CharEnumServer *message,
                  void *closure_data);
typedef void (*IWAserverGame__CharCreateClient_Closure)
                 (const IWAserverGame__CharCreateClient *message,
                  void *closure_data);
typedef void (*IWAserverGame__CharCreateServer_Closure)
                 (const IWAserverGame__CharCreateServer *message,
                  void *closure_data);
typedef void (*IWAserverGame__CharDeleteClient_Closure)
                 (const IWAserverGame__CharDeleteClient *message,
                  void *closure_data);
typedef void (*IWAserverGame__CharDeleteServer_Closure)
                 (const IWAserverGame__CharDeleteServer *message,
                  void *closure_data);
typedef void (*IWAserverGame__PlayerLoginClient_Closure)
                 (const IWAserverGame__PlayerLoginClient *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    i_waserver_game__result_code__descriptor;
extern const ProtobufCMessageDescriptor i_waserver_game__auth_challenge_server__descriptor;
extern const ProtobufCMessageDescriptor i_waserver_game__auth_session_client__descriptor;
extern const ProtobufCMessageDescriptor i_waserver_game__auth_response_server__descriptor;
extern const ProtobufCMessageDescriptor i_waserver_game__character__descriptor;
extern const ProtobufCMessageDescriptor i_waserver_game__char_enum_client__descriptor;
extern const ProtobufCMessageDescriptor i_waserver_game__char_enum_server__descriptor;
extern const ProtobufCMessageDescriptor i_waserver_game__char_create_client__descriptor;
extern const ProtobufCMessageDescriptor i_waserver_game__char_create_server__descriptor;
extern const ProtobufCMessageDescriptor i_waserver_game__char_delete_client__descriptor;
extern const ProtobufCMessageDescriptor i_waserver_game__char_delete_server__descriptor;
extern const ProtobufCMessageDescriptor i_waserver_game__player_login_client__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_iwa_5fgameserver_2eproto__INCLUDED */
