/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "iwa_gameserver.pb-c.h"
void   i_waserver_game__auth_challenge_server__init
                     (IWAserverGame__AuthChallengeServer         *message)
{
  static IWAserverGame__AuthChallengeServer init_value = I_WASERVER_GAME__AUTH_CHALLENGE_SERVER__INIT;
  *message = init_value;
}
size_t i_waserver_game__auth_challenge_server__get_packed_size
                     (const IWAserverGame__AuthChallengeServer *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &i_waserver_game__auth_challenge_server__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t i_waserver_game__auth_challenge_server__pack
                     (const IWAserverGame__AuthChallengeServer *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &i_waserver_game__auth_challenge_server__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t i_waserver_game__auth_challenge_server__pack_to_buffer
                     (const IWAserverGame__AuthChallengeServer *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &i_waserver_game__auth_challenge_server__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
IWAserverGame__AuthChallengeServer *
       i_waserver_game__auth_challenge_server__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (IWAserverGame__AuthChallengeServer *)
     protobuf_c_message_unpack (&i_waserver_game__auth_challenge_server__descriptor,
                                allocator, len, data);
}
void   i_waserver_game__auth_challenge_server__free_unpacked
                     (IWAserverGame__AuthChallengeServer *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &i_waserver_game__auth_challenge_server__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   i_waserver_game__auth_session_client__init
                     (IWAserverGame__AuthSessionClient         *message)
{
  static IWAserverGame__AuthSessionClient init_value = I_WASERVER_GAME__AUTH_SESSION_CLIENT__INIT;
  *message = init_value;
}
size_t i_waserver_game__auth_session_client__get_packed_size
                     (const IWAserverGame__AuthSessionClient *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &i_waserver_game__auth_session_client__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t i_waserver_game__auth_session_client__pack
                     (const IWAserverGame__AuthSessionClient *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &i_waserver_game__auth_session_client__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t i_waserver_game__auth_session_client__pack_to_buffer
                     (const IWAserverGame__AuthSessionClient *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &i_waserver_game__auth_session_client__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
IWAserverGame__AuthSessionClient *
       i_waserver_game__auth_session_client__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (IWAserverGame__AuthSessionClient *)
     protobuf_c_message_unpack (&i_waserver_game__auth_session_client__descriptor,
                                allocator, len, data);
}
void   i_waserver_game__auth_session_client__free_unpacked
                     (IWAserverGame__AuthSessionClient *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &i_waserver_game__auth_session_client__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   i_waserver_game__auth_response_server__init
                     (IWAserverGame__AuthResponseServer         *message)
{
  static IWAserverGame__AuthResponseServer init_value = I_WASERVER_GAME__AUTH_RESPONSE_SERVER__INIT;
  *message = init_value;
}
size_t i_waserver_game__auth_response_server__get_packed_size
                     (const IWAserverGame__AuthResponseServer *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &i_waserver_game__auth_response_server__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t i_waserver_game__auth_response_server__pack
                     (const IWAserverGame__AuthResponseServer *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &i_waserver_game__auth_response_server__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t i_waserver_game__auth_response_server__pack_to_buffer
                     (const IWAserverGame__AuthResponseServer *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &i_waserver_game__auth_response_server__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
IWAserverGame__AuthResponseServer *
       i_waserver_game__auth_response_server__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (IWAserverGame__AuthResponseServer *)
     protobuf_c_message_unpack (&i_waserver_game__auth_response_server__descriptor,
                                allocator, len, data);
}
void   i_waserver_game__auth_response_server__free_unpacked
                     (IWAserverGame__AuthResponseServer *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &i_waserver_game__auth_response_server__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   i_waserver_game__character__init
                     (IWAserverGame__Character         *message)
{
  static IWAserverGame__Character init_value = I_WASERVER_GAME__CHARACTER__INIT;
  *message = init_value;
}
size_t i_waserver_game__character__get_packed_size
                     (const IWAserverGame__Character *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &i_waserver_game__character__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t i_waserver_game__character__pack
                     (const IWAserverGame__Character *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &i_waserver_game__character__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t i_waserver_game__character__pack_to_buffer
                     (const IWAserverGame__Character *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &i_waserver_game__character__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
IWAserverGame__Character *
       i_waserver_game__character__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (IWAserverGame__Character *)
     protobuf_c_message_unpack (&i_waserver_game__character__descriptor,
                                allocator, len, data);
}
void   i_waserver_game__character__free_unpacked
                     (IWAserverGame__Character *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &i_waserver_game__character__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   i_waserver_game__char_enum_client__init
                     (IWAserverGame__CharEnumClient         *message)
{
  static IWAserverGame__CharEnumClient init_value = I_WASERVER_GAME__CHAR_ENUM_CLIENT__INIT;
  *message = init_value;
}
size_t i_waserver_game__char_enum_client__get_packed_size
                     (const IWAserverGame__CharEnumClient *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &i_waserver_game__char_enum_client__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t i_waserver_game__char_enum_client__pack
                     (const IWAserverGame__CharEnumClient *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &i_waserver_game__char_enum_client__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t i_waserver_game__char_enum_client__pack_to_buffer
                     (const IWAserverGame__CharEnumClient *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &i_waserver_game__char_enum_client__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
IWAserverGame__CharEnumClient *
       i_waserver_game__char_enum_client__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (IWAserverGame__CharEnumClient *)
     protobuf_c_message_unpack (&i_waserver_game__char_enum_client__descriptor,
                                allocator, len, data);
}
void   i_waserver_game__char_enum_client__free_unpacked
                     (IWAserverGame__CharEnumClient *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &i_waserver_game__char_enum_client__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   i_waserver_game__char_enum_server__init
                     (IWAserverGame__CharEnumServer         *message)
{
  static IWAserverGame__CharEnumServer init_value = I_WASERVER_GAME__CHAR_ENUM_SERVER__INIT;
  *message = init_value;
}
size_t i_waserver_game__char_enum_server__get_packed_size
                     (const IWAserverGame__CharEnumServer *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &i_waserver_game__char_enum_server__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t i_waserver_game__char_enum_server__pack
                     (const IWAserverGame__CharEnumServer *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &i_waserver_game__char_enum_server__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t i_waserver_game__char_enum_server__pack_to_buffer
                     (const IWAserverGame__CharEnumServer *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &i_waserver_game__char_enum_server__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
IWAserverGame__CharEnumServer *
       i_waserver_game__char_enum_server__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (IWAserverGame__CharEnumServer *)
     protobuf_c_message_unpack (&i_waserver_game__char_enum_server__descriptor,
                                allocator, len, data);
}
void   i_waserver_game__char_enum_server__free_unpacked
                     (IWAserverGame__CharEnumServer *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &i_waserver_game__char_enum_server__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   i_waserver_game__char_create_client__init
                     (IWAserverGame__CharCreateClient         *message)
{
  static IWAserverGame__CharCreateClient init_value = I_WASERVER_GAME__CHAR_CREATE_CLIENT__INIT;
  *message = init_value;
}
size_t i_waserver_game__char_create_client__get_packed_size
                     (const IWAserverGame__CharCreateClient *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &i_waserver_game__char_create_client__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t i_waserver_game__char_create_client__pack
                     (const IWAserverGame__CharCreateClient *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &i_waserver_game__char_create_client__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t i_waserver_game__char_create_client__pack_to_buffer
                     (const IWAserverGame__CharCreateClient *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &i_waserver_game__char_create_client__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
IWAserverGame__CharCreateClient *
       i_waserver_game__char_create_client__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (IWAserverGame__CharCreateClient *)
     protobuf_c_message_unpack (&i_waserver_game__char_create_client__descriptor,
                                allocator, len, data);
}
void   i_waserver_game__char_create_client__free_unpacked
                     (IWAserverGame__CharCreateClient *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &i_waserver_game__char_create_client__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   i_waserver_game__char_create_server__init
                     (IWAserverGame__CharCreateServer         *message)
{
  static IWAserverGame__CharCreateServer init_value = I_WASERVER_GAME__CHAR_CREATE_SERVER__INIT;
  *message = init_value;
}
size_t i_waserver_game__char_create_server__get_packed_size
                     (const IWAserverGame__CharCreateServer *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &i_waserver_game__char_create_server__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t i_waserver_game__char_create_server__pack
                     (const IWAserverGame__CharCreateServer *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &i_waserver_game__char_create_server__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t i_waserver_game__char_create_server__pack_to_buffer
                     (const IWAserverGame__CharCreateServer *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &i_waserver_game__char_create_server__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
IWAserverGame__CharCreateServer *
       i_waserver_game__char_create_server__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (IWAserverGame__CharCreateServer *)
     protobuf_c_message_unpack (&i_waserver_game__char_create_server__descriptor,
                                allocator, len, data);
}
void   i_waserver_game__char_create_server__free_unpacked
                     (IWAserverGame__CharCreateServer *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &i_waserver_game__char_create_server__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   i_waserver_game__char_delete_client__init
                     (IWAserverGame__CharDeleteClient         *message)
{
  static IWAserverGame__CharDeleteClient init_value = I_WASERVER_GAME__CHAR_DELETE_CLIENT__INIT;
  *message = init_value;
}
size_t i_waserver_game__char_delete_client__get_packed_size
                     (const IWAserverGame__CharDeleteClient *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &i_waserver_game__char_delete_client__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t i_waserver_game__char_delete_client__pack
                     (const IWAserverGame__CharDeleteClient *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &i_waserver_game__char_delete_client__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t i_waserver_game__char_delete_client__pack_to_buffer
                     (const IWAserverGame__CharDeleteClient *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &i_waserver_game__char_delete_client__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
IWAserverGame__CharDeleteClient *
       i_waserver_game__char_delete_client__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (IWAserverGame__CharDeleteClient *)
     protobuf_c_message_unpack (&i_waserver_game__char_delete_client__descriptor,
                                allocator, len, data);
}
void   i_waserver_game__char_delete_client__free_unpacked
                     (IWAserverGame__CharDeleteClient *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &i_waserver_game__char_delete_client__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   i_waserver_game__char_delete_server__init
                     (IWAserverGame__CharDeleteServer         *message)
{
  static IWAserverGame__CharDeleteServer init_value = I_WASERVER_GAME__CHAR_DELETE_SERVER__INIT;
  *message = init_value;
}
size_t i_waserver_game__char_delete_server__get_packed_size
                     (const IWAserverGame__CharDeleteServer *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &i_waserver_game__char_delete_server__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t i_waserver_game__char_delete_server__pack
                     (const IWAserverGame__CharDeleteServer *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &i_waserver_game__char_delete_server__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t i_waserver_game__char_delete_server__pack_to_buffer
                     (const IWAserverGame__CharDeleteServer *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &i_waserver_game__char_delete_server__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
IWAserverGame__CharDeleteServer *
       i_waserver_game__char_delete_server__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (IWAserverGame__CharDeleteServer *)
     protobuf_c_message_unpack (&i_waserver_game__char_delete_server__descriptor,
                                allocator, len, data);
}
void   i_waserver_game__char_delete_server__free_unpacked
                     (IWAserverGame__CharDeleteServer *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &i_waserver_game__char_delete_server__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   i_waserver_game__player_login_client__init
                     (IWAserverGame__PlayerLoginClient         *message)
{
  static IWAserverGame__PlayerLoginClient init_value = I_WASERVER_GAME__PLAYER_LOGIN_CLIENT__INIT;
  *message = init_value;
}
size_t i_waserver_game__player_login_client__get_packed_size
                     (const IWAserverGame__PlayerLoginClient *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &i_waserver_game__player_login_client__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t i_waserver_game__player_login_client__pack
                     (const IWAserverGame__PlayerLoginClient *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &i_waserver_game__player_login_client__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t i_waserver_game__player_login_client__pack_to_buffer
                     (const IWAserverGame__PlayerLoginClient *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &i_waserver_game__player_login_client__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
IWAserverGame__PlayerLoginClient *
       i_waserver_game__player_login_client__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (IWAserverGame__PlayerLoginClient *)
     protobuf_c_message_unpack (&i_waserver_game__player_login_client__descriptor,
                                allocator, len, data);
}
void   i_waserver_game__player_login_client__free_unpacked
                     (IWAserverGame__PlayerLoginClient *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &i_waserver_game__player_login_client__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor i_waserver_game__auth_challenge_server__field_descriptors[1] =
{
  {
    "seed",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(IWAserverGame__AuthChallengeServer, seed),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned i_waserver_game__auth_challenge_server__field_indices_by_name[] = {
  0,   /* field[0] = seed */
};
static const ProtobufCIntRange i_waserver_game__auth_challenge_server__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor i_waserver_game__auth_challenge_server__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "iWAserverGame.AuthChallengeServer",
  "AuthChallengeServer",
  "IWAserverGame__AuthChallengeServer",
  "iWAserverGame",
  sizeof(IWAserverGame__AuthChallengeServer),
  1,
  i_waserver_game__auth_challenge_server__field_descriptors,
  i_waserver_game__auth_challenge_server__field_indices_by_name,
  1,  i_waserver_game__auth_challenge_server__number_ranges,
  (ProtobufCMessageInit) i_waserver_game__auth_challenge_server__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor i_waserver_game__auth_session_client__field_descriptors[4] =
{
  {
    "build",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(IWAserverGame__AuthSessionClient, build),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "username",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(IWAserverGame__AuthSessionClient, username),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "seed",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(IWAserverGame__AuthSessionClient, seed),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "D",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(IWAserverGame__AuthSessionClient, d),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned i_waserver_game__auth_session_client__field_indices_by_name[] = {
  3,   /* field[3] = D */
  0,   /* field[0] = build */
  2,   /* field[2] = seed */
  1,   /* field[1] = username */
};
static const ProtobufCIntRange i_waserver_game__auth_session_client__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor i_waserver_game__auth_session_client__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "iWAserverGame.AuthSessionClient",
  "AuthSessionClient",
  "IWAserverGame__AuthSessionClient",
  "iWAserverGame",
  sizeof(IWAserverGame__AuthSessionClient),
  4,
  i_waserver_game__auth_session_client__field_descriptors,
  i_waserver_game__auth_session_client__field_indices_by_name,
  1,  i_waserver_game__auth_session_client__number_ranges,
  (ProtobufCMessageInit) i_waserver_game__auth_session_client__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor i_waserver_game__auth_response_server__field_descriptors[1] =
{
  {
    "result",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(IWAserverGame__AuthResponseServer, result),
    &i_waserver_game__result_code__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned i_waserver_game__auth_response_server__field_indices_by_name[] = {
  0,   /* field[0] = result */
};
static const ProtobufCIntRange i_waserver_game__auth_response_server__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor i_waserver_game__auth_response_server__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "iWAserverGame.AuthResponseServer",
  "AuthResponseServer",
  "IWAserverGame__AuthResponseServer",
  "iWAserverGame",
  sizeof(IWAserverGame__AuthResponseServer),
  1,
  i_waserver_game__auth_response_server__field_descriptors,
  i_waserver_game__auth_response_server__field_indices_by_name,
  1,  i_waserver_game__auth_response_server__number_ranges,
  (ProtobufCMessageInit) i_waserver_game__auth_response_server__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor i_waserver_game__character__field_descriptors[5] =
{
  {
    "cid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(IWAserverGame__Character, cid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(IWAserverGame__Character, name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "grade",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(IWAserverGame__Character, grade),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "race",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(IWAserverGame__Character, race),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nation",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(IWAserverGame__Character, nation),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned i_waserver_game__character__field_indices_by_name[] = {
  0,   /* field[0] = cid */
  2,   /* field[2] = grade */
  1,   /* field[1] = name */
  4,   /* field[4] = nation */
  3,   /* field[3] = race */
};
static const ProtobufCIntRange i_waserver_game__character__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor i_waserver_game__character__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "iWAserverGame.Character",
  "Character",
  "IWAserverGame__Character",
  "iWAserverGame",
  sizeof(IWAserverGame__Character),
  5,
  i_waserver_game__character__field_descriptors,
  i_waserver_game__character__field_indices_by_name,
  1,  i_waserver_game__character__number_ranges,
  (ProtobufCMessageInit) i_waserver_game__character__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor i_waserver_game__char_enum_client__field_descriptors[1] =
{
  {
    "reserved",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(IWAserverGame__CharEnumClient, reserved),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned i_waserver_game__char_enum_client__field_indices_by_name[] = {
  0,   /* field[0] = reserved */
};
static const ProtobufCIntRange i_waserver_game__char_enum_client__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor i_waserver_game__char_enum_client__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "iWAserverGame.CharEnumClient",
  "CharEnumClient",
  "IWAserverGame__CharEnumClient",
  "iWAserverGame",
  sizeof(IWAserverGame__CharEnumClient),
  1,
  i_waserver_game__char_enum_client__field_descriptors,
  i_waserver_game__char_enum_client__field_indices_by_name,
  1,  i_waserver_game__char_enum_client__number_ranges,
  (ProtobufCMessageInit) i_waserver_game__char_enum_client__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor i_waserver_game__char_enum_server__field_descriptors[2] =
{
  {
    "char_num",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(IWAserverGame__CharEnumServer, char_num),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "characters",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(IWAserverGame__CharEnumServer, n_characters),
    PROTOBUF_C_OFFSETOF(IWAserverGame__CharEnumServer, characters),
    &i_waserver_game__character__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned i_waserver_game__char_enum_server__field_indices_by_name[] = {
  0,   /* field[0] = char_num */
  1,   /* field[1] = characters */
};
static const ProtobufCIntRange i_waserver_game__char_enum_server__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor i_waserver_game__char_enum_server__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "iWAserverGame.CharEnumServer",
  "CharEnumServer",
  "IWAserverGame__CharEnumServer",
  "iWAserverGame",
  sizeof(IWAserverGame__CharEnumServer),
  2,
  i_waserver_game__char_enum_server__field_descriptors,
  i_waserver_game__char_enum_server__field_indices_by_name,
  1,  i_waserver_game__char_enum_server__number_ranges,
  (ProtobufCMessageInit) i_waserver_game__char_enum_server__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor i_waserver_game__char_create_client__field_descriptors[3] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(IWAserverGame__CharCreateClient, name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "race",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(IWAserverGame__CharCreateClient, race),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nation",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(IWAserverGame__CharCreateClient, nation),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned i_waserver_game__char_create_client__field_indices_by_name[] = {
  0,   /* field[0] = name */
  2,   /* field[2] = nation */
  1,   /* field[1] = race */
};
static const ProtobufCIntRange i_waserver_game__char_create_client__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor i_waserver_game__char_create_client__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "iWAserverGame.CharCreateClient",
  "CharCreateClient",
  "IWAserverGame__CharCreateClient",
  "iWAserverGame",
  sizeof(IWAserverGame__CharCreateClient),
  3,
  i_waserver_game__char_create_client__field_descriptors,
  i_waserver_game__char_create_client__field_indices_by_name,
  1,  i_waserver_game__char_create_client__number_ranges,
  (ProtobufCMessageInit) i_waserver_game__char_create_client__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor i_waserver_game__char_create_server__field_descriptors[2] =
{
  {
    "result",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(IWAserverGame__CharCreateServer, result),
    &i_waserver_game__result_code__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cid",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(IWAserverGame__CharCreateServer, cid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned i_waserver_game__char_create_server__field_indices_by_name[] = {
  1,   /* field[1] = cid */
  0,   /* field[0] = result */
};
static const ProtobufCIntRange i_waserver_game__char_create_server__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor i_waserver_game__char_create_server__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "iWAserverGame.CharCreateServer",
  "CharCreateServer",
  "IWAserverGame__CharCreateServer",
  "iWAserverGame",
  sizeof(IWAserverGame__CharCreateServer),
  2,
  i_waserver_game__char_create_server__field_descriptors,
  i_waserver_game__char_create_server__field_indices_by_name,
  1,  i_waserver_game__char_create_server__number_ranges,
  (ProtobufCMessageInit) i_waserver_game__char_create_server__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor i_waserver_game__char_delete_client__field_descriptors[1] =
{
  {
    "cid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(IWAserverGame__CharDeleteClient, cid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned i_waserver_game__char_delete_client__field_indices_by_name[] = {
  0,   /* field[0] = cid */
};
static const ProtobufCIntRange i_waserver_game__char_delete_client__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor i_waserver_game__char_delete_client__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "iWAserverGame.CharDeleteClient",
  "CharDeleteClient",
  "IWAserverGame__CharDeleteClient",
  "iWAserverGame",
  sizeof(IWAserverGame__CharDeleteClient),
  1,
  i_waserver_game__char_delete_client__field_descriptors,
  i_waserver_game__char_delete_client__field_indices_by_name,
  1,  i_waserver_game__char_delete_client__number_ranges,
  (ProtobufCMessageInit) i_waserver_game__char_delete_client__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor i_waserver_game__char_delete_server__field_descriptors[1] =
{
  {
    "result",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(IWAserverGame__CharDeleteServer, result),
    &i_waserver_game__result_code__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned i_waserver_game__char_delete_server__field_indices_by_name[] = {
  0,   /* field[0] = result */
};
static const ProtobufCIntRange i_waserver_game__char_delete_server__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor i_waserver_game__char_delete_server__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "iWAserverGame.CharDeleteServer",
  "CharDeleteServer",
  "IWAserverGame__CharDeleteServer",
  "iWAserverGame",
  sizeof(IWAserverGame__CharDeleteServer),
  1,
  i_waserver_game__char_delete_server__field_descriptors,
  i_waserver_game__char_delete_server__field_indices_by_name,
  1,  i_waserver_game__char_delete_server__number_ranges,
  (ProtobufCMessageInit) i_waserver_game__char_delete_server__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor i_waserver_game__player_login_client__field_descriptors[1] =
{
  {
    "cid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(IWAserverGame__PlayerLoginClient, cid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned i_waserver_game__player_login_client__field_indices_by_name[] = {
  0,   /* field[0] = cid */
};
static const ProtobufCIntRange i_waserver_game__player_login_client__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor i_waserver_game__player_login_client__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "iWAserverGame.PlayerLoginClient",
  "PlayerLoginClient",
  "IWAserverGame__PlayerLoginClient",
  "iWAserverGame",
  sizeof(IWAserverGame__PlayerLoginClient),
  1,
  i_waserver_game__player_login_client__field_descriptors,
  i_waserver_game__player_login_client__field_indices_by_name,
  1,  i_waserver_game__player_login_client__number_ranges,
  (ProtobufCMessageInit) i_waserver_game__player_login_client__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue i_waserver_game__result_code__enum_values_by_number[9] =
{
  { "SUCCESS", "I_WASERVER_GAME__RESULT_CODE__SUCCESS", 0 },
  { "UNKNOWN_ERROR", "I_WASERVER_GAME__RESULT_CODE__UNKNOWN_ERROR", 10 },
  { "UNPACK_MESSAGE_ERROR", "I_WASERVER_GAME__RESULT_CODE__UNPACK_MESSAGE_ERROR", 20 },
  { "AUTH_RESPONSE_DB_QUERY_ERROR", "I_WASERVER_GAME__RESULT_CODE__AUTH_RESPONSE_DB_QUERY_ERROR", 100 },
  { "AUTH_RESPONSE_ACCOUNT_NOEXIST", "I_WASERVER_GAME__RESULT_CODE__AUTH_RESPONSE_ACCOUNT_NOEXIST", 101 },
  { "AUTH_RESPONSE_HASH_CHECK_ERROR", "I_WASERVER_GAME__RESULT_CODE__AUTH_RESPONSE_HASH_CHECK_ERROR", 102 },
  { "CHAR_CREATE_ILLEGAL_NAME", "I_WASERVER_GAME__RESULT_CODE__CHAR_CREATE_ILLEGAL_NAME", 200 },
  { "CHAR_CREATE_DB_INSERT_ERROR", "I_WASERVER_GAME__RESULT_CODE__CHAR_CREATE_DB_INSERT_ERROR", 201 },
  { "CHAR_DELETE_DB_DELETE_ERROR", "I_WASERVER_GAME__RESULT_CODE__CHAR_DELETE_DB_DELETE_ERROR", 210 },
};
static const ProtobufCIntRange i_waserver_game__result_code__value_ranges[] = {
{0, 0},{10, 1},{20, 2},{100, 3},{200, 6},{210, 8},{0, 9}
};
const ProtobufCEnumValueIndex i_waserver_game__result_code__enum_values_by_name[9] =
{
  { "AUTH_RESPONSE_ACCOUNT_NOEXIST", 4 },
  { "AUTH_RESPONSE_DB_QUERY_ERROR", 3 },
  { "AUTH_RESPONSE_HASH_CHECK_ERROR", 5 },
  { "CHAR_CREATE_DB_INSERT_ERROR", 7 },
  { "CHAR_CREATE_ILLEGAL_NAME", 6 },
  { "CHAR_DELETE_DB_DELETE_ERROR", 8 },
  { "SUCCESS", 0 },
  { "UNKNOWN_ERROR", 1 },
  { "UNPACK_MESSAGE_ERROR", 2 },
};
const ProtobufCEnumDescriptor i_waserver_game__result_code__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "iWAserverGame.resultCode",
  "resultCode",
  "IWAserverGame__ResultCode",
  "iWAserverGame",
  9,
  i_waserver_game__result_code__enum_values_by_number,
  9,
  i_waserver_game__result_code__enum_values_by_name,
  6,
  i_waserver_game__result_code__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
